# Generated by Django 5.2.4 on 2025-08-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
